database:
  mysql:
    root:
      password:
    wordpress:
      database:
      user:
      password:
    nextcloud:
      database:
      user:
      password:
  redis:
    root:
      password:
service:
  wordpress:
    server_name:
  nextcloud:
    username:
    password:
    server_name:
  jenkins:
    server_name:

