database:
  mysql:
    root_password:
    wordpress_database:
    wordpress_user:
    wordpress_password:
    nextcloud_database:
    nextcloud_user:
    nextcloud_password:
  redis:
    root_password:
service:
  wordpress:
    server_name:
  nextcloud:
    server_name:
  jenkins:
    server_name:

