database:
  mysql:
    root_password:
    wordpress_user:
    wordpress_password:
    nextcloud_user:
    nextcloud_password:
  redis:
    root_password:
service:
  wordpress:
    username:
    password:
    email:
    plugins:
  nextcloud:
    username:
    password:
    email:
  jenkins:
    username:
    password:
    email:
