version: "3.8"

services:
  db_mysql:
    container_name: dbservice_mysql
    image: bitnami/mysql:latest
    command:
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data_mysql:/bitnami/mysql/data
    restart: always
    environment:
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATE: utf8mb4_unicode_ci
      MYSQL_ROOT_PASSWORD: /run/secrets/secret_db_mysql_root_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - database_service

  db_redis:
    container_name: dbservice_redis
    image: bitnami/redis:latest
    volumes:
      - db_data_redis:/bitnami/redis/data
    restart: always
    environment:
      REDIS_PASSWORD: /run/secrets/secret_db_redis_root_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - database_service

  db_interface_phpmyadmin:
    container_name: db_interface_phpmyadmin
    image: bitnami/phpmyadmin:latest
    environment:
      DATABASE_HOST: db_mysql
      DATABASE_PORT_NUMBER: 3306
      DATABASE_ALLOW_NO_PASSWORD: no
    networks:
      - proxy
      - database_service
      - database_service_interface

  security_service_vault:
    container_name: security_service_vault
    image: vault:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - service
      - database_service
      - database_service_interface

  service_wordpress:
    container_name: service_wordpress
    image: bitnami/wordpress
    depends_on:
      - db_mysql
      - db_redis
    volumes:
      - service_main_wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: /run/secrets/secret_db_mysql_wordpress_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - database_service

  service_owncloud:
    container_name: service_owncloud
    image: bitnami/owncloud:latest
    depends_on:
      - db_mysql
      - db_redis
    volumes:
      - service_data_owncloud_apps:/var/www/html/apps
      - service_data_owncloud_config:/var/www/html/config
      - service_data_owncloud_data:/var/www/html/data
    restart: always
    environment:
      OWNCLOUD_USERNAME: /run/secrets/secret_service_owncloud_username
      OWNCLOUD_PASSWORD: /run/secrets/secret_service_owncloud_password
      OWNCLOUD_EMAIL: /run/secrets/secret_service_owncloud_email
      OWNCLOUD_DATABASE_NAME: owncloud
      OWNCLOUD_DATABASE_USER: owncloud
      OWNCLOUD_DATABASE_PASSWORD: /run/secrets/secret_db_mysql_owncloud_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - database_service

  service_jenkins:
    container_name: service_jenkins
    image: bitnami/jenkins:latest
    volumes:
      - service_data_jenkins:/bitnami/jenkins
    restart: always
    environment:
      JENKINS_USERNAME: /run/secrets/secret_service_jenkins_username
      JENKINS_PASSWORD: /run/secrets/secret_service_jenkins_password
      JENKINS_EMAIL: /run/secrets/secret_service_jenkins_email
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - database_service

  proxy:
    container_name: service_proxy
    image: nginx:latest
    depends_on:
      - service_wordpress
      - service_owncloud
      - service_jenkins
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy

secrets:
  secret_db_mysql_root_password:
    file: ./secrets/secret_db_mysql_root_password
  secret_db_mysql_wordpress_password:
    file: ./secrets/secret_db_mysql_wordpress_password
  secret_db_mysql_owncloud_password:
    file: ./secrets/secret_db_mysql_owncloud_password
  secret_db_redis_root_password:
    file: ./secrets/secret_db_redis_root_password
  secret_service_owncloud_username:
    file: ./secrets/secret_service_owncloud_username
  secret_service_owncloud_password:
    file: ./secrets/secret_service_owncloud_password
  secret_service_owncloud_email:
    file: ./secrets/secret_service_owncloud_email
  secret_service_jenkins_username:
    file: ./secrets/secret_service_jenkins_username
  secret_service_jenkins_password:
    file: ./secrets/secret_service_jenkins_password
  secret_service_jenkins_email:
    file: ./secrets/secret_service_jenkins_email

volumes:
  db_data_mysql:
    name: db_data_mysql
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/database-service/mysql/data
      o: bind

  db_data_redis:
    name: db_data_redis
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/database-service/redis/data
      o: bind

  service_main_wordpress:
    name: service_main_wordpress
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/wordpress/main
      o: bind

  service_data_owncloud_apps:
    name: service_data_owncloud_apps
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/owncloud/apps
      o: bind

  service_data_owncloud_config:
    name: service_data_owncloud_config
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/owncloud/config
      o: bind

  service_data_owncloud_data:
    name: service_data_owncloud_data
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/owncloud/data
      o: bind

  service_data_jenkins:
    name: service_data_jenkins
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/jenkins/data
      o: bind

networks:
  proxy:
    name: network_proxy
    driver: bridge
  service:
    name: network_service
    driver: bridge
  database_service:
    name: network_database_service
    driver: bridge
  database_service_interface:
    name: network_database_service_interface
    driver: bridge