version: "3.8"

services:
  database_mysql:
    container_name: database_mysql
    image: mysql:latest
    cap_add:
      - SYS_NICE
    secrets:
      - database_mysql_root_password
      - database_mysql_wordpress_database
      - database_mysql_wordpress_user
      - database_mysql_wordpress_password
      - database_mysql_nextcloud_database
      - database_mysql_nextcloud_user
      - database_mysql_nextcloud_password
    volumes:
      - database_data_mysql:/var/lib/mysql
      - /etc/satellite-core/database/mysql/data:/var/lib/mysql
      - database_config_mysql:/etc/mysql/conf.d
      - ${PWD}/blueprint/database/mysql/config:/etc/mysql/conf.d
      - database_init_mysql:/docker-entrypoint-initdb.d
      - ${PWD}/blueprint/database/mysql/init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/database_mysql_root_password
    networks:
      - security
      - database

  database_redis:
    container_name: database_redis
    build:
      context: ./blueprint/database/redis
      dockerfile: Dockerfile-Redis
    secrets:
      - database_redis_root_password
    volumes:
      - database_data_redis:/data
      - /etc/satellite-core/database/redis/data:/data
    environment:
      REDIS_ROOT_PASSWORD_FILE: /run/secrets/database_redis_root_password
    restart: always
    networks:
      - security
      - database

  #security_consul:
  #  container_name: security_consul
  #  image: consul:latest
  #  volumes:
  #    - security_consul_config:/consul/config
  #    - ${PWD}/blueprint/security/consul/config:/consul/config
  #    - security_consul_data:/consul/data
  #    - /etc/satellite-core/security/consul/data:/consul/data
  #  restart: always
  #  networks:
  #    - security
  #
  #security_vault:
  #  container_name: security_vault
  #  image: vault:latest
  #  volumes:
  #    - security_vault_config:/vault/config
  #    - ${PWD}/blueprint/security/vault/config:/vault/config
  #    - security_vault_logs:/vault/logs
  #    - /etc/satellite-core/security/vault/logs:/vault/logs
  #    - security_vault_file:/vault/file
  #    - /etc/satellite-core/security/vault/file:/vault/file
  #  restart: always
  #  networks:
  #    - proxy
  #    - security

  service_wordpress:
    container_name: service_wordpress
    image: wordpress:latest
    depends_on:
      - database_mysql
      - database_redis
    secrets:
      - database_mysql_wordpress_database
      - database_mysql_wordpress_user
      - database_mysql_wordpress_password
    volumes:
      - service_core_wordpress:/var/www/html
      - /etc/satellite-core/service/wordpress/core:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: database_mysql
      WORDPRESS_DB_NAME_FILE: /run/secrets/database_mysql_wordpress_database
      WORDPRESS_DB_USER_FILE: /run/secrets/database_mysql_wordpress_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/database_mysql_wordpress_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - security
      - database

  service_nextcloud:
    container_name: service_nextcloud
    image: nextcloud:latest
    depends_on:
      - database_mysql
      - database_redis
    secrets:
      - database_mysql_nextcloud_database
      - database_mysql_nextcloud_user
      - database_mysql_nextcloud_password
      - database_redis_root_password
      - service_nextcloud_username
      - service_nextcloud_password
    volumes:
      - service_core_nextcloud:/var/www/html
      - /etc/satellite-core/service/nextcloud/core:/var/www/html
    restart: always
    environment:
      MYSQL_HOST: database_mysql
      MYSQL_DATABASE_FILE: /run/secrets/database_mysql_nextcloud_database
      MYSQL_USER_FILE: /run/secrets/database_mysql_nextcloud_user
      MYSQL_PASSWORD_FILE: /run/secrets/database_mysql_nextcloud_password
      NEXTCLOUD_ADMIN_USER_FILE: /run/secrets/service_nextcloud_username
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/service_nextcloud_password
      REDIS_HOST: database_redis
      REDIS_HOST_PASSWORD_FILE: /run/secrets/database_redis_root_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - security
      - database

  service_jenkins:
    container_name: service_jenkins
    image: jenkins/jenkins:jdk11
    volumes:
      - service_core_jenkins:/var/jenkins_home
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - security

  proxy_nginx:
    container_name: proxy_nginx
    image: bitnami/nginx:latest
    depends_on:
      - service_wordpress
    volumes:
      #- /etc/core/proxy/nginx/config/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
      - proxy_nginx_server_blocks:/opt/bitnami/nginx/conf/server_blocks
      - ${PWD}/blueprint/proxy/nginx/server_blocks:/opt/bitnami/nginx/conf/server_blocks
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy

secrets:
  database_mysql_root_password:
    file: ./secrets/database_mysql_root_password
  database_mysql_wordpress_database:
    file: ./secrets/database_mysql_wordpress_database
  database_mysql_wordpress_user:
    file: ./secrets/database_mysql_wordpress_user
  database_mysql_wordpress_password:
    file: ./secrets/database_mysql_wordpress_password
  database_mysql_nextcloud_database:
    file: ./secrets/database_mysql_nextcloud_database
  database_mysql_nextcloud_user:
    file: ./secrets/database_mysql_nextcloud_user
  database_mysql_nextcloud_password:
    file: ./secrets/database_mysql_nextcloud_password
  database_redis_root_password:
    file: ./secrets/database_redis_root_password
  service_nextcloud_username:
    file: ./secrets/service_nextcloud_username
  service_nextcloud_password:
    file: ./secrets/service_nextcloud_password

volumes:
  database_data_mysql:
    name: database_data_mysql
    driver: local

  database_config_mysql:
    name: database_data_mysql
    driver: local

  database_init_mysql:
    name: database_data_mysql
    driver: local

  database_data_redis:
    name: database_data_mysql
    driver: local

  # security_vault_config:
  #   name: security_vault_config
  #   driver: local
  #
  # security_vault_logs:
  #   name: security_vault_logs
  #   driver: local
  #
  # security_vault_file:
  #   name: security_vault_file
  #   driver: local

  service_core_wordpress:
    name: service_core_wordpress
    driver: local

  service_core_nextcloud:
    name: service_core_nextcloud
    driver: local

  service_core_jenkins:
    name: service_core_jenkins
    driver: local

  proxy_nginx_server_blocks:
    name: proxy_nginx_server_blocks
    driver: local

networks:
  database:
    driver: bridge
  security:
    driver: bridge
  service:
    driver: bridge
  proxy:
    driver: bridge