version: "3.8"

services:
  db_mysql:
    container_name: dbservice_mysql
    image: mysql:latest
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data_mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret_db_mysql_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: /run/secrets/secret_db_mysql_wordpress_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - dbservice

  db_redis:
    container_name: dbservice_redis
    image: bitnami/redis:latest
    volumes:
      - db_data_redis:/bitnami/redis/data
    restart: always
    environment:
      REDIS_PASSWORD: /run/secrets/secret_db_redis_root_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - dbservice

  service_wordpress:
    container_name: service_wordpress
    image: wordpress:latest
    depends_on:
      - db_mysql
      - db_redis
    volumes:
      - service_main_wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: /run/secrets/secret_service_wordpress_root_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - dbservice

  service_owncloud:
    container_name: service_owncloud
    image: owncloud:latest
    volumes:
      - service_data_owncloud_apps:/var/www/html/apps
      - service_data_owncloud_config:/var/www/html/config
      - service_data_owncloud_data:/var/www/html/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - dbservice

  service_jenkins:
    container_name: service_jenkins
    image: bitnami/jenkins:latest
    volumes:
      - service_data_jenkins:/bitnami/jenkins
    restart: always
    environment:
      JENKINS_USERNAME: /run/secrets/secret_service_jenkins_username
      JENKINS_PASSWORD: /run/secrets/secret_service_jenkins_password
      JENKINS_EMAIL: /run/secrets/secret_service_jenkins_email
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - dbservice

  proxy:
    container_name: service_proxy
    image: nginx:latest
    depends_on:
      - service_wordpress
      - service_owncloud
      - service_jenkins
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy

secrets:
  secret_db_mysql_root_password:
    external: true
  secret_db_mysql_wordpress_password:
    external: true
  secret_db_redis_root_password:
    external: true
  secret_service_wordpress_root_password:
    external: true
  secret_service_jenkins_username:
    external: true
  secret_service_jenkins_password:
    external: true
  secret_service_jenkins_email:
    external: true

volumes:
  db_data_mysql:
    name: db_data_mysql
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/database/mysql/data
      o: bind

  db_data_redis:
    name: db_data_redis
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/database/redis/data
      o: bind

  service_main_wordpress:
    name: service_data_wordpress
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/wordpress/main
      o: bind

  service_data_owncloud_apps:
    name: service_data_owncloud_apps
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/owncloud/apps
      o: bind

  service_data_owncloud_config:
    name: service_data_owncloud_config
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/owncloud/config
      o: bind

  service_data_owncloud_data:
    name: service_data_owncloud_data
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/owncloud/data
      o: bind

  service_data_jenkins:
    name: service_data_jenkins
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/owncloud/data
      o: bind

networks:
  proxy:
    name: network_proxy
  service:
    name: network_service
  dbservice:
    name: network_dbservice