version: "3.8"

services:
  database_mysql:
    container_name: database_mysql
    image: mysql:latest
    cap_add:
      - SYS_NICE
    secrets:
      - database_mysql_root_password
      - database_mysql_wordpress_database
      - database_mysql_wordpress_user
      - database_mysql_wordpress_password
      - database_mysql_nextcloud_database
      - database_mysql_nextcloud_user
      - database_mysql_nextcloud_password
    volumes:
      - database_mysql_data:/var/lib/mysql
      - /etc/satellite-core/database/mysql/data:/var/lib/mysql
      - database_mysql_config:/etc/mysql/conf.d
      - ${PWD}/blueprint/database/mysql/config:/etc/mysql/conf.d
      - database_mysql_init:/docker-entrypoint-initdb.d
      - ${PWD}/blueprint/database/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/database_mysql_root_password
    restart: always
    networks:
      - database

  database_redis:
    container_name: database_redis
    image: redis:latest
    volumes:
      - database_redis_data:/data
      - /etc/satellite-core/database/redis/data:/data
    restart: always
    networks:
      - database

  database_adminer:
    container_name: database_adminer
    image: adminer:latest
    environment:
      ADMINER_DESIGN: "dracula"
    restart: always
    networks:
      - database
      - proxy

  security_postgresql:
    container_name: security_postgresql
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "ssl=off"
    secrets:
      - security_postgresql_root_user
      - security_postgresql_root_password
    volumes:
      - security_postgresql_data:/var/lib/postgresql/data
      - /etc/satellite-core/security/postgresql/data:/var/lib/postgresql/data
      - security_postgresql_cert:/var/lib/postgresql/cert
      - ${PWD}/blueprint/security/postgresql/cert:/var/lib/postgresql/cert
      - security_postgresql_init:/docker-entrypoint-initdb.d
      - ${PWD}/blueprint/security/postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER_FILE: /run/secrets/security_postgresql_root_user
      POSTGRES_PASSWORD_FILE: /run/secrets/security_postgresql_root_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: "vault"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - security

  security_vault:
    container_name: security_vault
    image: vault:latest
    command:
      - "vault"
      - "server"
      - "-config"
      - "/vault/config/vault_config.hcl"
    depends_on:
      - security_postgresql
    cap_add:
      - IPC_LOCK
    secrets:
      - security_postgresql_root_user
      - security_postgresql_root_password
    volumes:
      - security_vault_config:/vault/config
      - ${PWD}/blueprint/security/vault/config:/vault/config
      - security_vault_logs:/vault/logs
      - /etc/satellite-core/security/vault/logs:/vault/logs
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    restart: always
    networks:
      - security
      - database
      - service
      - proxy

  service_wordpress:
    container_name: service_wordpress
    image: wordpress:latest
    depends_on:
      - database_mysql
      - database_redis
    secrets:
      - database_mysql_wordpress_database
      - database_mysql_wordpress_user
      - database_mysql_wordpress_password
    volumes:
      - service_wordpress_core:/var/www/html
      - /etc/satellite-core/service/wordpress/core:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database_mysql
      WORDPRESS_DB_NAME_FILE: /run/secrets/database_mysql_wordpress_database
      WORDPRESS_DB_USER_FILE: /run/secrets/database_mysql_wordpress_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/database_mysql_wordpress_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    restart: always
    networks:
      - proxy
      - service
      - database

  service_nextcloud:
    container_name: service_nextcloud
    image: nextcloud:latest
    depends_on:
      - database_mysql
      - database_redis
    secrets:
      - database_mysql_nextcloud_database
      - database_mysql_nextcloud_user
      - database_mysql_nextcloud_password
      - service_nextcloud_username
      - service_nextcloud_password
    volumes:
      - service_nextcloud_core:/var/www/html
      - /etc/satellite-core/service/nextcloud/core:/var/www/html
    environment:
      MYSQL_HOST: database_mysql
      MYSQL_DATABASE_FILE: /run/secrets/database_mysql_nextcloud_database
      MYSQL_USER_FILE: /run/secrets/database_mysql_nextcloud_user
      MYSQL_PASSWORD_FILE: /run/secrets/database_mysql_nextcloud_password
      NEXTCLOUD_ADMIN_USER_FILE: /run/secrets/service_nextcloud_username
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/service_nextcloud_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    restart: always
    networks:
      - proxy
      - service
      - database

  service_jenkins:
    container_name: service_jenkins
    image: jenkins/jenkins:jdk11
    volumes:
      - service_jenkins_core:/var/jenkins_home
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    restart: always
    networks:
      - proxy
      - service

  proxy_nginx:
    container_name: proxy_nginx
    image: bitnami/nginx:latest
    depends_on:
      - service_wordpress
    volumes:
      #- /etc/core/proxy/nginx/config/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
      - proxy_nginx_server_blocks:/opt/bitnami/nginx/conf/server_blocks
      - ${PWD}/blueprint/proxy/nginx/server_blocks:/opt/bitnami/nginx/conf/server_blocks
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    restart: always
    networks:
      - proxy

secrets:
  security_postgresql_root_user:
    file: ./secrets/security_postgresql_root_user
  security_postgresql_root_password:
    file: ./secrets/security_postgresql_root_password
  database_mysql_root_password:
    file: ./secrets/database_mysql_root_password
  database_mysql_wordpress_database:
    file: ./secrets/database_mysql_wordpress_database
  database_mysql_wordpress_user:
    file: ./secrets/database_mysql_wordpress_user
  database_mysql_wordpress_password:
    file: ./secrets/database_mysql_wordpress_password
  database_mysql_nextcloud_database:
    file: ./secrets/database_mysql_nextcloud_database
  database_mysql_nextcloud_user:
    file: ./secrets/database_mysql_nextcloud_user
  database_mysql_nextcloud_password:
    file: ./secrets/database_mysql_nextcloud_password
  service_nextcloud_username:
    file: ./secrets/service_nextcloud_username
  service_nextcloud_password:
    file: ./secrets/service_nextcloud_password

volumes:
  database_mysql_data:
    name: database_mysql_data
    driver: local

  database_mysql_config:
    name: database_mysql_config
    driver: local

  database_mysql_init:
    name: database_mysql_init
    driver: local

  database_redis_data:
    name: database_redis_data
    driver: local

  security_postgresql_data:
    name: security_postgresql_data
    driver: local

  security_postgresql_cert:
    name: security_postgresql_cert
    driver: local

  security_postgresql_init:
    name: security_postgresql_init
    driver: local

  security_vault_config:
    name: security_vault_config
    driver: local

  security_vault_logs:
    name: security_vault_logs
    driver: local

  service_wordpress_core:
    name: service_wordpress_core
    driver: local

  service_nextcloud_core:
    name: service_nextcloud_core
    driver: local

  service_jenkins_core:
    name: service_jenkins_core
    driver: local

  proxy_nginx_server_blocks:
    name: proxy_nginx_server_blocks
    driver: local

networks:
  database:
    driver: bridge
  security:
    driver: bridge
  service:
    driver: bridge
  proxy:
    driver: bridge