version: "3.8"

services:
  database_mysql:
    container_name: database_mysql
    image: bitnami/mysql:latest
    volumes:
      - database_data_mysql:/bitnami/mysql/data
    restart: always
    secrets:
      - secret_db_mysql_root_password
    environment:
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATE: utf8mb4_unicode_ci
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_ROOT_PASSWORD: /run/secrets/secret_db_mysql_root_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - database_service

  database_redis:
    container_name: database_redis
    image: bitnami/redis:latest
    volumes:
      - database_data_redis:/bitnami/redis/data
    restart: always
    secrets:
      - secret_db_redis_root_password
    environment:
      REDIS_PASSWORD: /run/secrets/secret_db_redis_root_password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - database_service

  database_interface_phpmyadmin:
    container_name: db_interface_phpmyadmin
    image: bitnami/phpmyadmin:latest
    depends_on:
      - database_mysql
    environment:
      DATABASE_HOST: database_mysql
      DATABASE_PORT_NUMBER: 3306
      DATABASE_ALLOW_NO_PASSWORD: no
    networks:
      - proxy
      - database_service

  security_service_vault:
    container_name: security_service_vault
    image: vault:latest
    volumes:
      - vault_logs:/vault/logs
      - vault_file:/vault/file
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - database_service

  service_wordpress:
    container_name: service_wordpress
    image: bitnami/wordpress:latest
    depends_on:
      - database_mysql
      - database_redis
    volumes:
      - service_core_wordpress:/bitnami/wordpress
    restart: always
    secrets:
      - secret_db_mysql_root_password
      - secret_db_mysql_wordpress_password
      - secret_service_wordpress_username
      - secret_service_wordpress_password
      - secret_service_wordpress_email
      - secret_service_wordpress_plugins
    environment:
      MYSQL_CLIENT_FLAVOR: mysql
      MYSQL_CLIENT_DATABASE_HOST: database_mysql
      MYSQL_CLIENT_DATABASE_ROOT_PASSWORD: /run/secrets/secret_db_mysql_root_password
      MYSQL_CLIENT_CREATE_DATABASE_NAME: wordpress
      MYSQL_CLIENT_CREATE_DATABASE_USER: wordpress
      MYSQL_CLIENT_CREATE_DATABASE_PASSWORD: /run/secrets/secret_db_mysql_wordpress_password
      PHP_POST_MAX_SIZE: 250M
      PHP_UPLOAD_MAX_FILESIZE: 250M
      WORDPRESS_USERNAME: /run/secrets/secret_service_wordpress_username
      WORDPRESS_PASSWORD: /run/secrets/secret_service_wordpress_password
      WORDPRESS_EMAIL: /run/secrets/secret_service_wordpress_email
      WORDPRESS_FIRST_NAME: Lee
      WORDPRESS_LAST_NAME: Arthur
      WORDPRESS_BLOG_NAME: Protogalaxy
      WORDPRESS_PLUGINS: /run/secrets/secret_service_wordpress_plugins
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - database_service

  service_owncloud:
    container_name: service_owncloud
    image: bitnami/owncloud:latest
    depends_on:
      - database_mysql
      - database_redis
    volumes:
      - service_data_owncloud_apps:/var/www/html/apps
      - service_data_owncloud_config:/var/www/html/config
      - service_data_owncloud_data:/var/www/html/data
    restart: always
    secrets:
      - secret_db_mysql_owncloud_password
      - secret_service_owncloud_username
      - secret_service_owncloud_password
      - secret_service_owncloud_email
    environment:
      MYSQL_CLIENT_FLAVOR: mysql
      MYSQL_CLIENT_DATABASE_HOST: database_mysql
      MYSQL_CLIENT_DATABASE_ROOT_PASSWORD: /run/secrets/secret_db_mysql_root_password
      MYSQL_CLIENT_CREATE_DATABASE_NAME: owncloud
      MYSQL_CLIENT_CREATE_DATABASE_USER: owncloud
      MYSQL_CLIENT_CREATE_DATABASE_PASSWORD: /run/secrets/secret_db_mysql_owncloud_password
      OWNCLOUD_USERNAME: /run/secrets/secret_service_owncloud_username
      OWNCLOUD_PASSWORD: /run/secrets/secret_service_owncloud_password
      OWNCLOUD_EMAIL: /run/secrets/secret_service_owncloud_email
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - database_service

  service_jenkins:
    container_name: service_jenkins
    image: bitnami/jenkins:latest
    depends_on:
      - database_mysql
      - database_redis
    volumes:
      - service_data_jenkins:/bitnami/jenkins
    restart: always
    secrets:
      - secret_service_jenkins_username
      - secret_service_jenkins_password
      - secret_service_jenkins_email
    environment:
      JENKINS_USERNAME: /run/secrets/secret_service_jenkins_username
      JENKINS_PASSWORD: /run/secrets/secret_service_jenkins_password
      JENKINS_EMAIL: /run/secrets/secret_service_jenkins_email
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy
      - service
      - database_service

  proxy:
    container_name: proxy_nginx
    image: bitnami/nginx:latest
    depends_on:
      - service_wordpress
      - service_owncloud
      - service_jenkins
    volumes:
      - proxy_server_blocks:/opt/bitnami/nginx/conf/server_blocks/
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
        tag: "{{.Name}}_{{.ImageName}}_{{.ID}}"
    networks:
      - proxy

secrets:
  secret_db_mysql_root_password:
    file: ./secrets/secret_db_mysql_root_password
  secret_db_mysql_wordpress_password:
    file: ./secrets/secret_db_mysql_wordpress_password
  secret_db_mysql_owncloud_password:
    file: ./secrets/secret_db_mysql_owncloud_password
  secret_db_redis_root_password:
    file: ./secrets/secret_db_redis_root_password
  secret_service_wordpress_username:
    file: ./secrets/secret_service_wordpress_username
  secret_service_wordpress_password:
    file: ./secrets/secret_service_wordpress_password
  secret_service_wordpress_email:
    file: ./secrets/secret_service_wordpress_email
  secret_service_wordpress_plugins:
    file: ./secrets/secret_service_wordpress_plugins
  secret_service_owncloud_username:
    file: ./secrets/secret_service_owncloud_username
  secret_service_owncloud_password:
    file: ./secrets/secret_service_owncloud_password
  secret_service_owncloud_email:
    file: ./secrets/secret_service_owncloud_email
  secret_service_jenkins_username:
    file: ./secrets/secret_service_jenkins_username
  secret_service_jenkins_password:
    file: ./secrets/secret_service_jenkins_password
  secret_service_jenkins_email:
    file: ./secrets/secret_service_jenkins_email

volumes:
  database_data_mysql:
    name: database_data_mysql
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/database-service/mysql/data
      o: bind

  database_data_redis:
    name: database_data_redis
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/database-service/redis/data
      o: bind

  vault_logs:
    name: vault_logs
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/vault/logs
      o: bind

  vault_file:
    name: vault_file
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/vault/file
      o: bind

  service_core_wordpress:
    name: service_core_wordpress
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/wordpress/core
      o: bind

  service_data_owncloud_apps:
    name: service_data_owncloud_apps
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/owncloud/apps
      o: bind

  service_data_owncloud_config:
    name: service_data_owncloud_config
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/owncloud/config
      o: bind

  service_data_owncloud_data:
    name: service_data_owncloud_data
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/owncloud/data
      o: bind

  service_data_jenkins:
    name: service_data_jenkins
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/service/jenkins/data
      o: bind

  proxy_server_blocks:
    name: proxy_server_blocks
    driver: local
    driver_opts:
      type: none
      device: /etc/satellite-core/proxy/server_blocks
      o: bind

networks:
  proxy:
    name: network_proxy
    driver: bridge
  service:
    name: network_service
    driver: bridge
  database_service:
    name: network_database
    driver: bridge