satellite-password:
  dbservice:
    mysql:
      root_password:
      wordpress_password:
      owncloud_password:
    redis:
      root_password:
  service:
    owncloud:
      username:
      password:
      email:
    jenkins:
      username:
      password:
      email:
