database:
  mysql:
    root_password:
    wordpress_password:
    owncloud_password:
  redis:
    root_password:
service:
  wordpress:
    username:
    password:
    email:
    plugins:
  owncloud:
    username:
    password:
    email:
  jenkins:
    username:
    password:
    email:
