FROM redis:latest

MAINTAINER SolitudeRA@GitHub.com

COPY redis.conf /usr/local/etc/redis/redis.conf

COPY ./docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]